# Generated by Django 5.0.6 on 2024-07-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("reference", models.IntegerField(unique=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Apartments", "Apartments"),
                            ("Commercial", "Commercial"),
                            ("Land", "Land"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Madrid", "Madrid"),
                            ("Barcelona", "Barcelona"),
                            ("Valencia", "Valencia"),
                            ("Seville", "Seville"),
                            ("Bilbao", "Bilbao"),
                            ("Malaga", "Malaga"),
                            ("Granada", "Granada"),
                            ("Alicante", "Alicante"),
                            ("Cordoba", "Cordoba"),
                            ("Zaragoza", "Zaragoza"),
                        ],
                        default="Madrid",
                        max_length=50,
                    ),
                ),
                ("general_information", models.TextField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("area", models.IntegerField()),
                ("price", models.IntegerField()),
                ("garden", models.BooleanField()),
                ("swimming_pool", models.BooleanField()),
                ("parking", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(max_length=60)),
                ("hero_subtitle", models.CharField(max_length=100)),
                ("facebook_url", models.CharField(max_length=200)),
                ("instagram_url", models.CharField(max_length=200)),
                ("phone_numbers", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.property",
                    ),
                ),
            ],
        ),
    ]
