# Generated by Django 5.0.6 on 2024-07-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
