# Generated by Django 5.0.6 on 2024-07-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_property_address_property_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="property",
            name="longitude",
        ),
        migrations.AddField(
            model_name="property",
            name="embed_map_url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
