# Generated by Django 5.0.6 on 2024-07-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_property_latitude_remove_property_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="embed_map_url",
        ),
    ]
