# Generated by Django 5.0.6 on 2024-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_property_embed_map_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("Casablanca", "Casablanca"),
                    ("Rabat", "Rabat"),
                    ("Fes", "Fes"),
                    ("Marrakesh", "Marrakesh"),
                    ("Tangier", "Tangier"),
                    ("Agadir", "Agadir"),
                    ("Meknes", "Meknes"),
                    ("Oujda", "Oujda"),
                    ("Tetouan", "Tetouan"),
                    ("Kenitra", "Kenitra"),
                    ("Safi", "Safi"),
                    ("Nador", "Nador"),
                    ("Beni Mellal", "Beni Mellal"),
                    ("Taza", "Taza"),
                    ("Laayoune", "Laayoune"),
                    ("Dakhla", "Dakhla"),
                    ("Essaouira", "Essaouira"),
                    ("El Jadida", "El Jadida"),
                    ("Settat", "Settat"),
                    ("Mohammedia", "Mohammedia"),
                ],
                default="Casablanca",
                max_length=50,
            ),
        ),
    ]
