# Generated by Django 5.0.6 on 2024-07-30 11:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_property_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
