# Generated by Django 5.0.6 on 2024-07-30 12:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_propertyimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=14)),
                ("email", models.CharField(max_length=14)),
            ],
        ),
    ]
