# Generated by Django 5.0.6 on 2024-07-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_partner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Partner",
            new_name="Member",
        ),
    ]
