# Generated by Django 5.0.6 on 2024-08-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_partner_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=20),
        ),
    ]
