# Generated by Django 5.0.6 on 2024-06-27 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("reference", models.IntegerField(unique=True)),
                ("property_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("general_information", models.TextField()),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("area", models.IntegerField()),
                ("distance_to_sea", models.IntegerField()),
                ("price", models.IntegerField()),
                ("garden", models.BooleanField()),
                ("swimming_pool", models.BooleanField()),
                ("parking", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.property",
                    ),
                ),
            ],
        ),
    ]
