# Generated by Django 5.0.6 on 2024-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(max_length=60)),
                ("hero_subtitle", models.CharField(max_length=100)),
                ("facebook_url", models.CharField(max_length=200)),
                ("instagram_url", models.CharField(max_length=200)),
                ("phone_numbers", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.CharField(max_length=60)),
            ],
        ),
    ]
