# Generated by Django 5.0.6 on 2024-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_property_options_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
