# Generated by Django 5.0.6 on 2024-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_booking_created_at_message_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="location",
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("Madrid", "Madrid"),
                    ("Barcelona", "Barcelona"),
                    ("Valencia", "Valencia"),
                    ("Seville", "Seville"),
                    ("Bilbao", "Bilbao"),
                    ("Malaga", "Malaga"),
                    ("Granada", "Granada"),
                    ("Alicante", "Alicante"),
                    ("Cordoba", "Cordoba"),
                    ("Zaragoza", "Zaragoza"),
                ],
                default="Madrid",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Commercial", "Commercial"),
                    ("Land", "Land"),
                ],
                max_length=50,
            ),
        ),
    ]
